# Site settings
title: Luciano Borguetti
email: lucianoborguetti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A little about Linux, virtualization, docker, networking, security ...
baseurl: ""
url: "http://lborguetti.github.io"
twitter_username: lborguetti
github_username:  lborguetti

# Build settings
markdown: kramdown
